config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  resources :ailments, only: [:create, :show]
  resources :carts
  resources :line_items
  post "order_complete" => "carts#order_complete"
  resources :reviews, only: [:create, :new, :edit, :update, :destroy]
  resources :service_areas, only: [:create, :new, :index, :show]

end

app/models/ailment.rb
class Ailment < ActiveRecord::Base
	has_many :line_items
	has_many :reviews
end

app/controllers/ailments_controller.rb
class AilmentsController <ApplicationController

  def show
     @selected_ailment = Ailment.find(params[:id])
     @review = Review.new
     @reviews = @selected_ailment.reviews.order('created_at DESC')
  end

def create
  @ailment = Ailment.new(ailment_params)
end


private

def ailment_params
  params.require(:ailment).permit(:name, :description, :shopping_list)
end

end 

app/views/ailments/show.html.erb
<!-- after we select our ailment on the root page welcome#index we are directed to our ailments show page where we shop for our ailment -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>

<div class="jumbotron">
<div class="ailments">
<h1><%= @selected_ailment.name %></h1>
<br>
<%= @selected_ailment.description %>
<br>
<br>
<%= @selected_ailment.shopping_list %>
<br>
<br>
Price: <%= number_to_currency @selected_ailment.price %> * Delivery fee not included!
</div>
<br>
<br>
<center>
 <%= link_to "Purchase Remedy Kit", line_items_path(ailment_id: @selected_ailment.id), method: :post, class: "btn btn-success btn-md" %>
 <%= link_to 'Back', :back, class: "btn btn-default btn-md" %>

 </center>
</div>
<br>

 <div class="panel panel-default">
	<div class="panel-heading">
		REVIEWS
</div>

	<div class="panel-body">
		<%= render @review %>
	</div>

	<% if current_user %> 
	<div class="panel panel-info">
		<div class="panel-heading">
			Write a Review
		</div>
		<div class="panel-body">
			<%= render "reviews/form" %>
		</div>
	</div>
	<% end %>

</div>