config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  resources :ailments, only: [:create, :show]
  resources :carts
  resources :line_items
  post "order_complete" => "carts#order_complete"
  resources :reviews, only: [:create, :new, :edit, :update, :destroy]
  resources :service_areas, only: [:create, :new, :index, :show]

end

app/controllers/welcome_controller.rb
class WelcomeController <ApplicationController

  def index
    @ailments = Ailment.all
    @check_service_area = ServiceArea.new

  end

end 

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ginger Ails</title>
</head>
<body>
<center>
<div class="font_title">
<h1>Ginger Ails</h1>
</div>
<div class="font_subtitle">
<h2>On call for what ails you!</h2>
</div>
<br>
<br>

<% if current_user %>
 <div class="btn-group">
  <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    SELECT YOUR AILMENT <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
  <% Ailment.all.each do |ailment| %>
    <li><%= link_to ailment.name, ailment_path(id: ailment.id) %></li>
    <% end %>
  </ul>
  </div>
  </center>
<% else %>
  <button type="button" class="btn btn-warning btn-lg" data-toggle="modal" data-target="#myModal">
  Check Your Address
  </button>
<% end %>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Check Your Address</h4>
      </div>
      <div class="modal-body">
        <%= render 'service_areas/form' %>
      </div>
    </div>
  </div>
</div>
</body>
</html>