config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  resources :ailments, only: [:create, :show]
  resources :carts
  resources :line_items
  post "order_complete" => "carts#order_complete"
  resources :reviews, only: [:create, :new, :edit, :update, :destroy]
  resources :service_areas, only: [:create, :new, :index, :show]

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  def add_ailment(ailment_id)
	# grabbing line_items through association setting the current_item to the product_id 
  current_item = line_items.find_by(ailment_id: ailment_id)
  #if there is a value in here then it knows its in the cart
  if current_item
 	current_item.quantity += 1
  else
 	current_item = line_items.build(ailment_id: ailment_id)
  end
  #regardless of which path we want to retun the current item, ruby returns the last thing
  current_item
 end

  def subtotal
    line_items.to_a.sum{ |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
before_action :authenticate_user!
before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json

  def order_complete
    @cart = Cart.find(params[:cart_id])
    @amount = (@cart.subtotal.to_f.round(2) * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Rails Stripe customer',
      :currency => 'usd'
    )
      @cart.destroy

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end

  def index
    @carts = Cart.all
  end

  def show
    @user = User.find_by(id: params[:id])  
    # the cart is not secure until we make sure you can only see a cart that matches you as a user
    # may need to drop your database after this is implemented rake db:reset add products and users
      unless current_user.id == @cart.user_id
      flash[:notice] = "You don't have access to that order!"
      redirect_to root_path
      end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /carts/1
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /carts/1
  def destroy
    #make sure we can only destroy our own cart and make sure the session id is also destroyed by setting it to nil
    @cart.destroy if @cart.id == session[:cart_id]
    #session is a rails method that allows us to store temp data without saving it to a dbase
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'You successfully emptied your shopping cart!' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:user_id)
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/order_complete.html.erb
<div class="jumbotron">
<center>
<h2 class="order_complete">Thank you for your order!</h2>

<h5 class="order_details">
  Order # <%= @cart.id %> will be shipping to you, at <%= @current_user.address %> as soon as possible! 
  <br>
  <br>
  We aim to have your order at your door in 30 minutes or less! 
</h5>
</center>
</div>

app/views/carts/show.html.erb
<div class="jumbotron">
<h2 class="shopping_title">Your Shopping Cart</h2>
<br>
<table class="table">
<thead>
	<tr>
		<th>Ailment</th>
		<th>Quantity</th>
		<th>Unit Price</th>
		<th>Total Price</th>
	</tr>
</thead>
<tbody>
	<% @cart.line_items.each do |item| %>
	<tr>
		<td><%= item.ailment.name %></td>
		<td><%= item.quantity %></td>
		<td><%= number_to_currency item.ailment.price %></td>
		<td><%= number_to_currency item.total_price %></td>
	</tr>
	<% end %>

</tbody>
</table>
<h3 class="subtotal">Order Subtotal: <%= number_to_currency @cart.subtotal %></h3>
<center>
<%= link_to "Add Another Remedy Kit", root_path, class: "btn btn-default btn-sm" %>
<%= link_to "Empty Cart", @cart, method: :delete, class: "btn btn-warning btn-sm" %>

<div style = 'display:inline-block;'>
  <%= form_tag order_complete_path do %>
    <div>
      <%= hidden_field_tag :cart_id, @cart.id %>
    </div>

    <script src="https://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @cart.id %>"
    data-amount="<%= (@cart.subtotal.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>
<br>
<br>
<div class="delivered_to">
This order will be delivered to: <%= current_user.name %> at <%= current_user.address %>
</center>
</div>
</div>