config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'welcome#index'
  resources :ailments, only: [:create, :show]
  resources :carts
  resources :line_items
  post "order_complete" => "carts#order_complete"
  resources :reviews, only: [:create, :new, :edit, :update, :destroy]
  resources :service_areas, only: [:create, :new, :index, :show]

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :ailment

  def total_price
    ailment.price * quantity
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
	include CurrentCart
	before_action :authenticate_user!
	before_action :set_cart, only: [:create]
    before_action :set_line_item, only: [:index]

	def index
		@line_item = LineItem.all
	end

	def create
		ailment = Ailment.find(params[:ailment_id])
		@line_item = @cart.add_ailment(ailment.id)
		respond_to do |format|
		  if @line_item.save
			format.html {redirect_to @line_item.cart}
		  else
			format.html {render :new}
		  end
        end
	end

def new
	@line_item = LineItem.new
end

private

  def set_line_item
	@line_item = LineItem.find(params[:id])
  end

  def line_item_params
	params.require(:line_item).permit(:ailment_id, :quantity, :cart_id)
  end

end

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Ailment</th>
      <th>Quantity</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.ailment %></td>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>